apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: timber-backend
        image: nbrown/timber-backend:1.3
        ports:
        - containerPort: 8080
